config/routes.rb
Tvbud::Application.routes.draw do

  resources :comments

  resources :activities

  root to: "main#index"

  scope "/auth" do
    match "/:provider/callback", to: "sessions#create", via: [:get, :post]
    get "", to: "sessions#new", as: 'auth'
    get "/register", to: "auth#register", as: 'register'
    post "/new", to: "auth#new"
    post "/sign_in", to: "auth#login"
    get "/failure", to: "sessions#failure"
    get "/confirm_email", to: "auth#confirm_email"
    get "/logout", to: "sessions#destroy", as: 'logout'
  end
  get 'tags/:tag', to: 'items#search', as: 'tag'
  resources :identities

  scope "/:locale" do
    resources :articles
    get '/:id/like', to: 'items#like', as: 'like_item'
    get '/:id/rate', to: 'items#rate', as: 'rate_item'
    scope :users do 
      get '/index', to: 'users#index', as: 'users'
      get '/:id', to: 'users#show', as: 'user'
      get '/:id/subscribe', to: 'users#subscribe', as: 'subscribe_user'
    end
    resources :videos do
       get 'approve', :action => 'approve'
    end
    get '/:slug', to: 'items#show', as: 'item_slugged'
  end
  match "/:locale/videos/upload", :to => 'videos#upload', via: [:post], as: 'upload_video'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  acts_as :item
  after_save :create_necessary_additions
  
  
  def create_necessary_additions
    create_activity
  end
  
  def create_activity
    @activity = Activity.new
    @activity.item = self.item
    @activity.user = self.item.user
    @activity.content = self.content
    @activity.activity_type = 'comment'
    @activity.save
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    @comment.save
    redirect_to :back
  end


  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:content, :parent_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.haml
= form_for @comment do |f|
  - if @comment.errors.any?
    #error_explanation
      %h2= "#{pluralize(@comment.errors.count, "error")} prohibited this comment from being saved:"
      %ul
        - @comment.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :content
    = f.text_area :content
  .actions
    = f.submit 'Save'

app/views/comments/edit.html.haml
%h1 Editing comment

= render 'form'

= link_to 'Show', @comment
\|
= link_to 'Back', comments_path

app/views/comments/index.html.haml
%h1 Listing comments

%table
  %tr
    %th Content
    %th
    %th
    %th

  - @comments.each do |comment|
    %tr
      %td= comment.content
      %td= link_to 'Show', comment
      %td= link_to 'Edit', edit_comment_path(comment)
      %td= link_to 'Destroy', comment, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Comment', new_comment_path

app/views/comments/new.html.haml
%h1 New comment

= render 'form'

= link_to 'Back', comments_path

app/views/comments/show.html.haml
%p#notice= notice

%p
  %b Content:
  = @comment.content

= link_to 'Edit', edit_comment_path(@comment)
\|
= link_to 'Back', comments_path