config/routes.rb
Tvbud::Application.routes.draw do

  resources :comments

  resources :activities

  root to: "main#index"

  scope "/auth" do
    match "/:provider/callback", to: "sessions#create", via: [:get, :post]
    get "", to: "sessions#new", as: 'auth'
    get "/register", to: "auth#register", as: 'register'
    post "/new", to: "auth#new"
    post "/sign_in", to: "auth#login"
    get "/failure", to: "sessions#failure"
    get "/confirm_email", to: "auth#confirm_email"
    get "/logout", to: "sessions#destroy", as: 'logout'
  end
  get 'tags/:tag', to: 'items#search', as: 'tag'
  resources :identities

  scope "/:locale" do
    resources :articles
    get '/:id/like', to: 'items#like', as: 'like_item'
    get '/:id/rate', to: 'items#rate', as: 'rate_item'
    scope :users do 
      get '/index', to: 'users#index', as: 'users'
      get '/:id', to: 'users#show', as: 'user'
      get '/:id/subscribe', to: 'users#subscribe', as: 'subscribe_user'
    end
    resources :videos do
       get 'approve', :action => 'approve'
    end
    get '/:slug', to: 'items#show', as: 'item_slugged'
  end
  match "/:locale/videos/upload", :to => 'videos#upload', via: [:post], as: 'upload_video'
end

app/models/article.rb
class Article < ActiveRecord::Base
  acts_as :item
  translates :name, :content
  after_save :create_necessary_additions
  
  extend FriendlyId
  friendly_id :slug
  
  def create_necessary_additions
    #reate_translation
    create_activity
  end
  
  def create_translation  
  end
  
  def create_activity
    @activity = Activity.new
    @activity.item = self.item
    @activity.user = self.item.user
    @activity.activity_type = 'add'
    @activity.save
  end
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :show, :destroy]
  before_action :set_to_translate, only: [:update]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    @article.item.user = current_user
    respond_to do |format|
      if @article.save
        @item_translation = ItemTranslation.new(translation_params)
        @item_translation.item_id = @article.item.id
        @item_translation.locale = params["language"]
        @item_translation.save
        
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render action: 'show', status: :created, location: @article }
      else
        format.html { render action: 'new' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    @item_translation = ItemTranslation.find_or_create_by_item_id_and_locale(@article.item.id, params["language"])
    @item_translation.update(translation_params)
    #render json: @item_translation
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end
  
  def translate
    render json: params
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @item_translation = ItemTranslation.friendly.find(params[:id])
      @item = @item_translation.item
      puts @item_translation.locale
      @article = Article.find(@item.as_item_id)
    end
    
    def set_to_translate
      @it = ItemTranslation.where(slug: params["id"]).first
      @item = @it.item
      @article = Article.find(@item.as_item_id)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit()
    end
    
    def translation_params
      params.require(:article).permit(:name, :content, :slug)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.haml
= form_for @article do |f|
  - if @article.errors.any?
    #error_explanation
      %h2= "#{pluralize(@article.errors.count, "error")} prohibited this article from being saved:"
      %ul
        - @article.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :content
    = f.text_area :content
    .field
    = f.label :slug
    = f.text_field :slug
    .field
    = label_tag :language
    = text_field_tag :language
  .actions
    = f.submit 'Save'

app/views/articles/edit.html.haml
%h1 Editing article

= render 'form'

= link_to 'Show', @article
\|
= link_to 'Back', articles_path

app/views/articles/index.html.haml
%h1 Listing articles

%table
  %tr
    %th Title
    %th Content
    %th
    %th
    %th
    %th
    %th

  - @articles.each do |article|
    %tr
      %td= article.name
      %td= article.content
      %td= link_to 'Show', item_slugged_path(article)
      %td= link_to 'Edit', edit_article_path(article)
      %td= link_to 'Destroy', article, :method => :delete, :data => { :confirm => 'Are you sure?' }
      %td= link_to 'Like article', like_item_path(article.item.id)
      %td= link_to 'Rate article', rate_item_path(article.item.id)

%br

= link_to 'New Article', new_article_path

app/views/articles/new.html.haml
%h1 New article

= render 'form'

= link_to 'Back', articles_path

app/views/articles/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @article.name
%p
  %b Content:
  = @article.content

= link_to 'Edit', edit_article_path(@article)
\|
= link_to 'Back', articles_path