config/routes.rb
Tvbud::Application.routes.draw do

  resources :comments

  resources :activities

  root to: "main#index"

  scope "/auth" do
    match "/:provider/callback", to: "sessions#create", via: [:get, :post]
    get "", to: "sessions#new", as: 'auth'
    get "/register", to: "auth#register", as: 'register'
    post "/new", to: "auth#new"
    post "/sign_in", to: "auth#login"
    get "/failure", to: "sessions#failure"
    get "/confirm_email", to: "auth#confirm_email"
    get "/logout", to: "sessions#destroy", as: 'logout'
  end
  get 'tags/:tag', to: 'items#search', as: 'tag'
  resources :identities

  scope "/:locale" do
    resources :articles
    get '/:id/like', to: 'items#like', as: 'like_item'
    get '/:id/rate', to: 'items#rate', as: 'rate_item'
    scope :users do 
      get '/index', to: 'users#index', as: 'users'
      get '/:id', to: 'users#show', as: 'user'
      get '/:id/subscribe', to: 'users#subscribe', as: 'subscribe_user'
    end
    resources :videos do
       get 'approve', :action => 'approve'
    end
    get '/:slug', to: 'items#show', as: 'item_slugged'
  end
  match "/:locale/videos/upload", :to => 'videos#upload', via: [:post], as: 'upload_video'
end

app/models/video.rb
class Video < ActiveRecord::Base
	acts_as :item

  def self.yt_session
    @yt_session ||= YouTubeIt::Client.new(:username => ENV['YOUTUBE_USERNAME'], :password =>  ENV['YOUTUBE_PASSWORD'], :dev_key => ENV['YOUTUBE_DEV_KEY'])
  end

  def self.token_form(params, nexturl)
    @yt_session ||= YouTubeIt::Client.new(:username => ENV['YOUTUBE_USERNAME'], :password =>  ENV['YOUTUBE_PASSWORD'], :dev_key => ENV['YOUTUBE_DEV_KEY'])
    options = video_options(params)
    @yt_session.upload_token(options, nexturl)
  end

  private
  def self.video_options(params)
    opts = {:provider => params[:provider]}
    opts.merge(:private => "true")
  end

end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  require 'youtube_it'
	include UsersHelper
	def index
		@videos = Video.all
	end

	def new
		@video = Video.new
  end

  def upload
    @video = Video.create
    @video.provider = params[:video['provider']]
    if @video
      @upload_info = YouTubeIt::Client.new.upload_token(params[:video],"onet.pl")
    else
      respond_to do |format|
        format.html { render "/videos/new" }
      end
    end
  end

	def create
		@video = Video.create(video_params)
		@video.user = current_user
		@video.save
		redirect_to videos_path, notice: "New video has been added!"
	end


	private
	    # Never trust parameters from the scary internet, only allow the white list through.
	    def video_params
	      params.require(:video).permit(:provider)
	    end
end

app/views/videos/index.html.haml
%h1 Videos
%p
	Total videos
	%strong= @videos.size
	= link_to t('videos.add_new'), new_video_path
%ul
- @videos.each do |video|
	%li
		= video.name
		(
		= video.id
		) - 
		= video.active
		added by 
		= video.user.displayed_name if video.user
		= 'unknown' unless video.user
		= raw video.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') 

app/views/videos/new.html.haml
%h1 New video
= form_for @video, :url => upload_video_path do |f|

	.field
		= f.label :provider
		= f.text_field :provider
	.field
		= f.submit :save

app/views/videos/upload.html.erb
<div class="block">
  <div class="secondary-navigation">
  </div>
  <div class="content">
    <h2 class="title"><%= t("web-app-theme.new", :default => "New")%> Video</h2>
    <div class="inner">
      <p>Step 2: upload a new video.</p>

      <%= form_tag @upload_info[:url], :multipart => true do %>
          <%= hidden_field_tag :token, @upload_info[:token] %>
          <%= label_tag :file %>
          <%= file_field_tag :file %>
          <%= submit_tag "Upload video" %>
      <% end %>
    </div>
  </div>
</div>