config/routes.rb
Tvbud::Application.routes.draw do

  resources :comments

  resources :activities

  root to: "main#index"

  scope "/auth" do
    match "/:provider/callback", to: "sessions#create", via: [:get, :post]
    get "", to: "sessions#new", as: 'auth'
    get "/register", to: "auth#register", as: 'register'
    post "/new", to: "auth#new"
    post "/sign_in", to: "auth#login"
    get "/failure", to: "sessions#failure"
    get "/confirm_email", to: "auth#confirm_email"
    get "/logout", to: "sessions#destroy", as: 'logout'
  end
  get 'tags/:tag', to: 'items#search', as: 'tag'
  resources :identities

  scope "/:locale" do
    resources :articles
    get '/:id/like', to: 'items#like', as: 'like_item'
    get '/:id/rate', to: 'items#rate', as: 'rate_item'
    scope :users do 
      get '/index', to: 'users#index', as: 'users'
      get '/:id', to: 'users#show', as: 'user'
      get '/:id/subscribe', to: 'users#subscribe', as: 'subscribe_user'
    end
    resources :videos do
       get 'approve', :action => 'approve'
    end
    get '/:slug', to: 'items#show', as: 'item_slugged'
  end
  match "/:locale/videos/upload", :to => 'videos#upload', via: [:post], as: 'upload_video'
end

app/models/activity.rb
class Activity < ActiveRecord::Base
  belongs_to :user
  belongs_to :item
  
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit, :update, :destroy]

  # GET /activities
  # GET /activities.json
  def index
    @activities = Activity.all
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(activity_params)

    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity, notice: 'Activity was successfully created.' }
        format.json { render action: 'show', status: :created, location: @activity }
      else
        format.html { render action: 'new' }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params.require(:activity).permit(:activity_type, :content)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_form.html.haml
= form_for @activity do |f|
  - if @activity.errors.any?
    #error_explanation
      %h2= "#{pluralize(@activity.errors.count, "error")} prohibited this activity from being saved:"
      %ul
        - @activity.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :activity_type
    = f.text_field :activity_type
  .field
    = f.label :content
    = f.text_field :content
  .actions
    = f.submit 'Save'

app/views/activities/edit.html.haml
%h1 Editing activity

= render 'form'

= link_to 'Show', @activity
\|
= link_to 'Back', activities_path

app/views/activities/index.html.haml
%h1 Listing activities

%table
  %tr
    %th Activity type
    %th Content
    %th
    %th
    %th

  - @activities.each do |activity|
    %tr
      %td= activity.activity_type
      %td= activity.content
      %td= link_to 'Show', activity
      %td= link_to 'Edit', edit_activity_path(activity)
      %td= link_to 'Destroy', activity, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Activity', new_activity_path

app/views/activities/new.html.haml
%h1 New activity

= render 'form'

= link_to 'Back', activities_path

app/views/activities/show.html.haml
%p#notice= notice

%p
  %b Activity type:
  = @activity.activity_type
%p
  %b Content:
  = @activity.content

= link_to 'Edit', edit_activity_path(@activity)
\|
= link_to 'Back', activities_path